experience/urls.py
from django.conf.urls import url
from . import views

app_name = 'experience'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<job_id>\d+)/$', views.detail, name='detail')
]

hamzaanas/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^qualification/', include('qualification.urls')),
    url(r'^experience/', include('experience.urls')),
    url(r'^skill/', include('skill.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

qualification/urls.py
from django.conf.urls import url
from . import views

app_name = 'qualification'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<degree_id>\d+)/$', views.detail, name='detail'),
]

skill/urls.py
from django.conf.urls import url
from . import views

app_name = 'skill'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index')
]

experience/models.py
from django.db import models


# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=100)
    image = models.FileField()
    url = models.URLField(max_length=200)
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Job(models.Model):
    title = models.CharField(max_length=100)
    date_from = models.DateField('From')
    date_to = models.DateField('To')
    description = models.TextField()
    comp = models.ForeignKey(Company, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title

qualification/models.py
from django.db import models


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=100)
    img = models.FileField()
    url = models.URLField(max_length=200)
    location = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Degree(models.Model):
    DEGREE_LEVEL_CHOICES = (
        ('High School', 'High School'),
        ('College', 'College'),
        ('Bachelors', 'Bachelors'),
        ('Masters', 'Masters')
    )
    name = models.CharField(max_length=100)
    level = models.CharField(max_length=50, choices=DEGREE_LEVEL_CHOICES)
    url = models.URLField(max_length=200)
    date_from = models.DateField('Year Started')
    date_to = models.DateField('Year Finished')
    school = models.ForeignKey(School, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=10)
    url = models.URLField(max_length=200)
    degree = models.ForeignKey(Degree, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.code + " - " + self.name


class CertBody(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=200)

    def __str__(self):
        return self.name


class Certification(models.Model):
    title = models.CharField(max_length=200)
    year = models.DateField('Year Completed')
    url = models.URLField(max_length=200)
    provider = models.ForeignKey(CertBody, models.SET_NULL, blank=True, null=True)
    school = models.ForeignKey(School, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title

skill/models.py
from django.db import models


# Create your models here.
class Specialization(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tool(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=50)
    specialization = models.ForeignKey(Specialization, models.SET_NULL, blank=True, null=True)
    language = models.ManyToManyField(Language, related_name='language')
    tools = models.ForeignKey(Tool, models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

experience/views.py
from django.core import serializers
from django.http import Http404, JsonResponse
from django.views import generic

# Create your views here.
from experience.models import Job, Company


class IndexView(generic.ListView):
    template_name = 'experience/index.html'

    def get_queryset(self):
        return Job.objects.all().order_by('-date_from')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['active'] = 'experience'
        # context['tagline'] = 'EXPERIENCE'
        return context


def detail(request, job_id):
    try:
        job = Job.objects.filter(pk=job_id)
        company = Company.objects.filter(pk=job[0].comp_id)
        context = {}
        if request.is_ajax():
            context['function'] = '[{"function_name": "experience"}]'
            context['job'] = serializers.serialize("json", job)
            context['company'] = serializers.serialize("json", company)
            return JsonResponse(context)
        else:
            raise Http404
    except Job.DoesNotExist:
        raise Http404

qualification/views.py
from django.core import serializers
from django.http import Http404, JsonResponse
from django.views import generic
from qualification.models import Degree, School, Course, Certification


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'qualification/index.html'

    def get_queryset(self):
        return Degree.objects.all().order_by('-date_to')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['certifications'] = Certification.objects.all().prefetch_related()
        context['active'] = 'qualification'
        # context['tagline'] = 'QUALIFICATIONS'
        return context

    # class DetailView(generic.DetailView):
    #     model = Degree
    #     template_name = 'qualification/detail.html'


def detail(request, degree_id):
    try:
        degree = Degree.objects.filter(pk=degree_id)
        school = School.objects.filter(pk=degree[0].school_id)
        course = Course.objects.filter(degree_id=degree_id)
        context = {}
        if request.is_ajax():
            context['function'] = '[{"function_name": "qualification"}]'
            context['degree'] = serializers.serialize("json", degree)
            context['school'] = serializers.serialize("json", school)
            context['course'] = serializers.serialize("json", course)
            return JsonResponse(context)
        else:
            raise Http404
    except Degree.DoesNotExist:
        raise Http404

skill/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic

from skill.models import Skill


class IndexView(generic.ListView):
    template_name = 'skill/index.html'

    def get_queryset(self):
        return Skill.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['active'] = 'skill'
        # context['tagline'] = 'SKILLS'
        print(context)
        return context

experience/templates/experience/base.html
{% extends 'base.html' %}
{% block body %}
    {% block content %}
    {% endblock %}
    {% include 'experience/detail.html' %}
{% endblock %}

experience/templates/experience/detail.html
{% extends 'detail.html' %}
{% block modalbody %}
    <div class="modal-body" id="modal-body">
        <div class="container-fluid no-padding">
            <div class="row">
                <div class="col-md-12">
                    <img class="detail-img img-responsive" src="">
                </div>
            </div>
        </div>
        <hr>
        <div class="modal-details container">
            <table class="display" cellspacing="0" width="100%">
                <tr>
                    <th>Title:</th>
                    <td id="title"></td>
                </tr>
                <tr>
                    <th>Company:</th>
                    <td id="company"></td>
                </tr>
                <tr>
                    <th>From:</th>
                    <td id="from"></td>
                </tr>
                <tr>
                    <th>To:</th>
                    <td id="to"></td>
                </tr>
                <tr>
                    <th>Location:</th>
                    <td id="location"></td>
                </tr>
            </table>
        </div>
        <hr class="slide">
        <div class="container">
            <div class="row detail-table">
                <span id="description"></span>
            </div>
        </div>
    </div>
{% endblock %}

experience/templates/experience/index.html
{% extends 'experience/base.html' %}
{% block content %}
    <div id="main" class="container">
        <div id="job">
            <h3>Professional Experience</h3>
            <br>
            <div class="row">
                {% if object_list %}
                    {% for job in object_list %}
                        <div class="col-xs-1 col-sm-3 card-container">
                            <div class="card  primary" data-id="{{ job.pk }}"
                                 data-url="{% url 'experience:detail' job.pk %}">
                                <div class="card-header  frame">
                                    <span class="helper"></span>
                                    <img class="card-img-top" src="{{ job.comp.image.url }}">
                                </div>
                                <div id="card-body" class="card-body">
                                    <h6 id="card-subtitle"
                                        class="card-subtitle mb-2 text-muted">{{ job.comp.name }}</h6>
                                    <h6 id="card-title" class="card-title">{{ job.title }}</h6>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h6>You don't have any jobs.</h6>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

qualification/templates/qualification/base.html
{% extends 'base.html' %}
{% block body %}
    {% block content %}
    {% endblock %}
    {% include 'qualification/detail.html' %}
{% endblock %}

qualification/templates/qualification/detail.html
{% extends 'detail.html' %}
{% block modalbody %}
    <div class="modal-body" id="modal-body">
        <div class="container-fluid no-padding">
            <div class="row">
                <div class="col-md-12">
                    <img class="detail-img img-responsive" src="">
                </div>
            </div>
        </div>
        <hr>
        <div class="modal-details container">
            <table class="display" cellspacing="0" width="100%">
                <tr>
                    <th>Name:</th>
                    <td id="degree"></td>
                </tr>
                <tr>
                    <th>Level:</th>
                    <td id="level"></td>
                </tr>
                <tr>
                    <th>Institution:</th>
                    <td id="institution"></td>
                </tr>
                <tr>
                    <th>Started:</th>
                    <td id="from"></td>
                </tr>
                <tr>
                    <th>Graduated:</th>
                    <td id="to"></td>
                </tr>
                <tr>
                    <th>Location:</th>
                    <td id="location"></td>
                </tr>
            </table>
        </div>
        <hr class="slide">
        <div class="container">
            <div class="row detail-table">
                <div id="first-half" class="list-group col-md-5">
                </div>
                <div id="break" class="list-group col-md-2">
                </div>
                <div id="second-half" class="list-group col-md-5">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

qualification/templates/qualification/index.html
{% extends 'qualification/base.html' %}
{% block content %}
    <div id="main" class="container">
        <div id="academic">
            <h3>Education</h3>
            <br>
            <div class="row">
                {% if degree_list %}
                    {% for degree in object_list %}
                        <div class="col-sm-6 col-md-3 card-container">
                            <div class="card primary" data-id="{{ degree.pk }}"
                                 data-url="{% url 'qualification:detail' degree.pk %}">
                                <div class="card-header frame">
                                    <img class="card-img-top" src="{{ degree.school.img.url }}">
                                </div>
                                <div id="card-body" class="card-body">
                                    <h6 id="card-subtitle"
                                        class="card-subtitle mb-2 text-muted">{{ degree.get_level_display }}</h6>
                                    <h6 id="card-title" class="card-title">{{ degree.name }}</h6>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <h6>You don't have any degrees.</h6>
                {% endif %}
            </div>
        </div>
        <div id="certifications">
            <h3>Certifications</h3>
            <br>
            <div class="row">
                {% if certifications %}
                    {% for cert in certifications %}
                        <div class="col-sm-6 col-md-3 ">
                            <div class="card h-100 secondary" data-id="{{ cert.pk }}"
                                 data-href="{{ cert.url }}">
                                <div class="card-header">
                                </div>
                                <div id="card-body" class="card-body">
                                    <h6 id="card-title" class="card-title">
                                        <a id="cert-title" href="{{ cert.url }}" target="_blank">
                                            {{ cert.title }}
                                        </a>
                                    </h6>
                                </div>
                                <ul class="list-group list-group-flush card-list">
                                    <li class="list-group-item card-subtitle text-muted">
                                        <a href="{{ cert.school.url }}" target="_blank">
                                            {{ cert.school }}
                                        </a>
                                    </li>
                                    <li class="list-group-item card-subtitle text-muted">
                                        <a href="{{ cert.provider.url }}" target="_blank">
                                            {{ cert.provider }}
                                        </a>
                                    </li>
                                    <li class="list-group-item card-subtitle text-muted">
                                        {{ cert.year|date:'F, Y' }}
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <br/>
                    {% endfor %}
                {% else %}
                    <h6>You don't have any certifications.</h6>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

skill/templates/skill/base.html
{% extends 'base.html' %}
{% block body %}
    {% block content %}
    {% endblock %}
{% endblock %}

skill/templates/skill/index.html
{% extends 'skill/base.html' %}
{% block content %}
    <div id="main" class="container">
        <div id="primary">
            <h3>Skills</h3>
            <br>
            <div class="row">
                {% if skill_list %}
                    {% for skill in skill_list %}
                        <div class="col-sm-6 col-md-3 card-container">
                            <div class="card h-100 secondary" data-id="{{ skill.pk }}">
                                <div class="card-header">
                                    {{ skill.specialization }}
                                </div>
                                <div id="card-body" class="card-body">
                                    <h6 id="card-title" class="card-title">
                                        {{ skill.name }}
                                    </h6>
                                </div>
                                <ul class="list-group list-group-flush card-list">
                                    <li class="list-group-item card-subtitle text-muted">
                                        {% for lang in skill.language.all %}
                                            {{ lang }}
                                        {% endfor %}
                                    </li>
                                    <li class="list-group-item card-subtitle text-muted">
                                        {{ skill.tools }}
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <br/>
                    {% endfor %}
                {% else %}
                    <h6>You don't have any skills.</h6>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% include 'header.html' %}
{% include 'nav.html' %}
{% include 'jumbotron.html' %}
{% block body %}
{% endblock %}
{% include 'footer.html' %}

templates/detail.html
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div id="modal-dialog .modal-dialog-centered" class="modal-dialog"> {# removed class modal-lg #}
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            {% block modalbody %}
            {% endblock %}
            <div class="modal-footer">
                <button type="button" data-active="{{ active }}" class="btn btn-primary view-detail">
                    {% if active == 'qualification' %}
                        View Courses
                    {% elif active == 'experience' %}
                        View Description
                    {% else %}
                        View Detail
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</div>

templates/footer.html
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-ms-1 col-centered">
                <div class="copyrights">
                    <p>Copyright © Hamza Anas</p>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.js"></script>
<script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
{% load staticfiles %}
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'qualification/js/qualification.js' %}"></script>
<script src="{% static 'experience/js/experience.js' %}"></script>
</body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Hamza Anas{% endblock %}</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
          integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

templates/jumbotron.html
<div class="jumbotron">
    <h1 class="display-4">Hello World...</h1>
</div>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Hamza Anas</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a {% if active == 'qualification' %} class="nav-link active" {% else %} class="nav-link" {% endif %}
                                                      href="{% url 'qualification:index' %}">Qualifications</a>
            </li>
            <li class="nav-item">
                <a {% if active == 'experience' %} class="nav-link active" {% else %} class="nav-link" {% endif %}
                                                   href="{% url 'experience:index' %}">Experience</a>
            </li>
            <li class="nav-item">
                <a {% if active == 'skill' %} class="nav-link active" {% else %} class="nav-link" {% endif %}
                                              href="{% url 'skill:index' %}">Skills</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Portfolio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Contact Me</a>
            </li>
        </ul>
    </div>
</nav>